services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    ports:
    - 9200:9200
    environment:
    - discovery.type=single-node
    - ELASTIC_PASSWORD=password123