up:
	docker compose up -d

down:
	docker compose down

stop:
	docker compose stop

start:
	docker compose start

ps:
	docker compose ps

web-kibana:
	open http://localhost:5601/app/dev_tools#/console/shell

web-elastic:
	open http://localhost:9200

data-setup:
	docker compose run --rm data-setup
