services:
  elastic:
    image: elasticsearch:9.0.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"

  kibana:
    image: kibana:9.0.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"